from test import employee_test

print("*****ADD EMPLOYE*****")
employee_test.test_add_employee()
print()
print()
print("*****EMPLOYEE DETEAILS*****")
employee_test.test_employee_details()
print()
print()
print("*****UPDATE EMPLOYEE*****")
employee_test.test_update_employee()
print()
print()
print("*****DELETE EMPLOYEE*****")
employee_test.test_delete_employee()
print()
print()
print("*****ALL EMPLOYEES*****")
employee_test.test_get_all_employees()