use smqa;

CREATE TABLE EMPLOYEE (
    `empID` VARCHAR(255) PRIMARY KEY,
    `empName` VARCHAR(255) NOT NULL,
    `empType` VARCHAR(255) NOT NULL
);

CREATE TABLE MENU (
    `itemID` VARCHAR(255) PRIMARY KEY,
    `itemName` VARCHAR(255) NOT NULL,
    `itemPrice` INT NOT NULL,
    `itemType` VARCHAR(255) NOT NULL
);


CREATE TABLE TABLES (
    `tableID` VARCHAR(255) PRIMARY KEY,
    `available` BOOLEAN DEFAULT TRUE,
    `empID` VARCHAR(255) NOT NULL,
    `quantity` INT NOT NULL DEFAULT 1,
    `seats` INT,
    FOREIGN KEY (empID) REFERENCES EMPLOYEE(empID)
);

CREATE TABLE WAITER (
    `waiterID` VARCHAR(255) PRIMARY KEY,
    `empID` VARCHAR(255) NOT NULL UNIQUE,
    FOREIGN KEY (empID) REFERENCES EMPLOYEE(empID)
);

CREATE TABLE CHEF (
    `chefID` VARCHAR(255) PRIMARY KEY,
    `empID` VARCHAR(255) NOT NULL UNIQUE,
    FOREIGN KEY (empID) REFERENCES EMPLOYEE(empID)
);

CREATE TABLE ORDERS (
    `orderID` VARCHAR(255) PRIMARY KEY,
    `itemID` VARCHAR(255) NOT NULL,
    `tableID` VARCHAR(255) NOT NULL,
    `waiterID` VARCHAR(255) NOT NULL,
    FOREIGN KEY (tableID) REFERENCES TABLES(tableID)
);

CREATE TABLE BILL (
    `billID` VARCHAR(255) PRIMARY KEY,
    `orderID` VARCHAR(255) NOT NULL,
    `tableID` VARCHAR(255) NOT NULL,
    FOREIGN KEY (tableID) REFERENCES TABLES(tableID),
    FOREIGN KEY (orderID) REFERENCES ORDERS(orderID)
);