INSERT INTO MENU VALUES("itemID", "itemName", "itemPrice", "itemType");
INSERT INTO MENU VALUES("1", "Plain Dosa", "5", "1");
INSERT INTO MENU VALUES("2", "Paneer Dosa", "6", "1");
INSERT INTO MENU VALUES("3", "Paneer Chilly Dosa", "7", "1");
INSERT INTO MENU VALUES("4", "Sweet Corn Chilly Dosa", "9", "1");
INSERT INTO MENU VALUES("5", "Green Peas Chilly Dosa", "10", "1");
INSERT INTO MENU VALUES("6", "Mushroom Dosa", "12", "1");
INSERT INTO MENU VALUES("7", "Baby Corn Dosa", "13", "1");
INSERT INTO MENU VALUES("8", "Cauliflower Dosa", "14", "1");
INSERT INTO MENU VALUES("9", "Palak Chilly Dosa", "15", "1");
INSERT INTO MENU VALUES("10", "Sehezwan Noodles Dosa", "16", "1");
INSERT INTO MENU VALUES("11", "Mysore Masala Dosa", "15", "1");
INSERT INTO MENU VALUES("12", "Mysore Cheese Dosa", "15", "1");
INSERT INTO MENU VALUES("13", "Pizza Dosa", "17", "1");
INSERT INTO MENU VALUES("14", "Allo Dosa", "17", "1");
INSERT INTO MENU VALUES("15", "Rava Dosa", "14", "1");
INSERT INTO MENU VALUES("16", "Family Dosa", "20", "1");
INSERT INTO MENU VALUES("17", "Onion Dosa", "6", "1");
INSERT INTO MENU VALUES("18", "Spring Roll Dosa", "8", "1");
INSERT INTO MENU VALUES("19", "Butter Naan", "12", "2");
INSERT INTO MENU VALUES("20", "Garlic Naan", "13", "2");
INSERT INTO MENU VALUES("21", "Onion Naan", "14", "2");
INSERT INTO MENU VALUES("22", "Aloo Naan", "16", "2");
INSERT INTO MENU VALUES("23", "Lacha Naan", "17", "2");
INSERT INTO MENU VALUES("24", "Cheese Naan", "18", "2");
INSERT INTO MENU VALUES("25", "Roti", "13", "2");
INSERT INTO MENU VALUES("26", "Kerala Porotta", "15", "2");
INSERT INTO MENU VALUES("27", "Bun Porotta", "14", "2");
INSERT INTO MENU VALUES("28", "Kizi Porotta", "18", "2");
INSERT INTO MENU VALUES("29", "Kothu Porotta", "19", "2");
INSERT INTO MENU VALUES("30", "Poori", "11", "2");
INSERT INTO MENU VALUES("31", "Cocktail Samosa", "10", "3");
INSERT INTO MENU VALUES("32", "Samosa chaat", "10", "3");
INSERT INTO MENU VALUES("33", "Batata Vada", "10", "3");
INSERT INTO MENU VALUES("34", "Bang Bang Cauliflower", "10", "3");
INSERT INTO MENU VALUES("35", "Tomato Soup", "10", "3");
INSERT INTO MENU VALUES("36", "Spinach Soup", "10", "3");
INSERT INTO MENU VALUES("37", "Cutlite", "10", "3");
INSERT INTO MENU VALUES("38", "Parupu vada", "10", "3");
INSERT INTO MENU VALUES("39", "Egg Spring Rolls", "5", "4");
INSERT INTO MENU VALUES("40", "Chicken Spring Rolls", "8", "4");
INSERT INTO MENU VALUES("41", "Chicken 65", "10", "4");
INSERT INTO MENU VALUES("42", "Chilli Chicken", "12", "4");
INSERT INTO MENU VALUES("43", "Chicken Drum Sticks", "13", "4");
INSERT INTO MENU VALUES("44", "Chicken Manchurian", "16", "4");
INSERT INTO MENU VALUES("45", "Pepper Chicken", "14", "4");
INSERT INTO MENU VALUES("46", "Chicken Lollipop", "15", "4");
INSERT INTO MENU VALUES("47", "Ginger Chicken", "14", "4");
INSERT INTO MENU VALUES("48", "Dream Nut Chicken", "15", "4");
INSERT INTO MENU VALUES("49", "Apolo Fish", "16", "4");
INSERT INTO MENU VALUES("50", "Ginger Fish", "18", "4");
INSERT INTO MENU VALUES("51", "Chicken Sangai", "18", "4");
INSERT INTO MENU VALUES("52", "Paneer Tikka", "20", "5");
INSERT INTO MENU VALUES("53", "Kadai Paneer", "20", "5");
INSERT INTO MENU VALUES("54", "Butter Paneer Masala", "21", "5");
INSERT INTO MENU VALUES("55", "Mutter Paneer", "24", "5");
INSERT INTO MENU VALUES("56", "Sev Tamatar", "25", "5");
INSERT INTO MENU VALUES("57", "Mix Veg", "22", "5");
INSERT INTO MENU VALUES("58", "Malai Kofta", "24", "5");
INSERT INTO MENU VALUES("59", "Aloo Gofta", "22", "5");
INSERT INTO MENU VALUES("60", "Dal Tadka", "22", "5");
INSERT INTO MENU VALUES("61", "Kaju Paneer", "22", "5");
INSERT INTO MENU VALUES("62", "Butter Chicken", "30", "6");
INSERT INTO MENU VALUES("63", "Kadai Chicken", "30", "6");
INSERT INTO MENU VALUES("64", "Chicken Tika Masala", "35", "6");
INSERT INTO MENU VALUES("65", "Bundel Khandi Chicken", "33", "6");
INSERT INTO MENU VALUES("66", "Chicken Home Style", "30", "6");
INSERT INTO MENU VALUES("67", "Egg Curry", "32", "6");
INSERT INTO MENU VALUES("68", "Chicken Curry", "34", "6");
INSERT INTO MENU VALUES("69", "Mutton Curry", "33", "6");
INSERT INTO MENU VALUES("70", "Fish Curry", "34", "6");
INSERT INTO MENU VALUES("71", "Fish Fry", "33", "6");
INSERT INTO MENU VALUES("72", "Mutton Keema", "35", "6");
INSERT INTO MENU VALUES("73", "Andhra Fish Curry", "33", "6");
INSERT INTO MENU VALUES("74", "Kerala Fish Curry", "36", "6");
INSERT INTO MENU VALUES("75", "Chocolate Cupcake", "10", "7");
INSERT INTO MENU VALUES("76", "Homemade Banoofee Pie", "10", "7");
INSERT INTO MENU VALUES("77", "Coppa Catalana", "10", "7");
INSERT INTO MENU VALUES("78", "Homemade Tiramisu", "12", "7");
INSERT INTO MENU VALUES("79", "Chocolotate Cake", "10", "7");
INSERT INTO MENU VALUES("80", "Lattice Applie Pie", "12", "7");
INSERT INTO MENU VALUES("81", "Gelati Misti", "11", "7");
INSERT INTO MENU VALUES("82", "Dirty Martini", "20", "8");
INSERT INTO MENU VALUES("83", "Manhattan", "21", "8");
INSERT INTO MENU VALUES("84", "B52", "22", "8");
INSERT INTO MENU VALUES("85", "Old Fashioned", "23", "8");
INSERT INTO MENU VALUES("86", "Harvey Wallbanger", "24", "8");
INSERT INTO MENU VALUES("87", "Black Forest Caake", "25", "8");
INSERT INTO MENU VALUES("88", "Blue Lagoon", "26", "8");
INSERT INTO MENU VALUES("89", "Sex On The Beach", "27", "8");
INSERT INTO MENU VALUES("90", "Mai Tai", "28", "8");
INSERT INTO MENU VALUES("91", "Mango Fusion", "20", "9");
INSERT INTO MENU VALUES("92", "Passion Tropic", "21", "9");
INSERT INTO MENU VALUES("93", "Margarita", "22", "9");
INSERT INTO MENU VALUES("94", "Orginal Mojito", "23", "9");
INSERT INTO MENU VALUES("95", "Watermelon Mojito", "24", "9");
INSERT INTO MENU VALUES("96", "Melon Mojito", "25", "9");
INSERT INTO MENU VALUES("97", "Mai Tai", "26", "9");
INSERT INTO MENU VALUES("98", "Arun Chocolate Icecream", "90", "10");
INSERT INTO MENU VALUES("99", "Arun Strawberry Icecream", "91", "10");
INSERT INTO MENU VALUES("100", "Arun Berry Icecream", "92", "10");
INSERT INTO MENU VALUES("101", "Arun Melon Icecream", "93", "10");
INSERT INTO MENU VALUES("102", "Arun Vanila Icecream", "94", "10");
INSERT INTO MENU VALUES("103", "Arun Cherry Icecream", "95", "10");
INSERT INTO MENU VALUES("104", "Arun Creamy Icecream", "96", "10");
INSERT INTO MENU VALUES("105", "Arun Matcha", "97", "10");
INSERT INTO MENU VALUES("106", "Arun Lemon Icecream", "98", "10");
INSERT INTO MENU VALUES("107", "Arun Toffee", "99", "10");